[package]
name = "apt-sync"
version = "0.3.0"
edition = "2024"
description = "Curated APT package manager for syncing dev environments"
license = "MIT"

[dependencies]

[profile.release]
strip = true
lto = true
