[package]
name = "apt-sync"
version = "0.5.1"
edition = "2024"
description = "Curated APT package manager for syncing dev environments"
license = "MIT"

[dependencies]

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
